FoodDl/FoodDelivery/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodDelivery.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }
        public int? CustomerId { get; set; }
        public DateTime AcceptanceDate { get; set; } = DateTime.Now;
        public Customer? Customers { get; set; }
        public int? DeliveryListId { get; set; }
        public DeliveryList? DeliveryList { get; set; }
        public ICollection<OrderProduct>? OrderProducts { get; set; }
    }

}

FoodDl/FoodDelivery/ViewModels/BasketViewModel.cs
namespace FoodDelivery.ViewModels
{
    public class BasketViewModel
    {
        public int ProductId { get; set; }

        public string? ProductName { get; set; }

        public float? Price { get; set; }

        public string? ImageUrl { get; set; }

        public float? FinalPrice { get; set; }
        public int Quantity { get; set; }
    }
}

FoodDl/FoodDelivery/ViewModels/OrderViewModel.cs
using System.Collections.Generic;

namespace FoodDelivery.ViewModels
{
    public class OrderViewModel
    {
        public List<OrderProductViewModel>? OrderProducts { get; set; }
        public float? TotalPrice { get; set; }
    }

    public class OrderProductViewModel
    {
        public int? ProductId { get; set; }
        public string? Name { get; set; }
        public float? Price { get; set; }
        public string? ImageUrl { get; set; }
        public int? Quantity { get; set; }
        public float? TotalPrice { get; set; }
    }
}

FoodDl/FoodDelivery/Controllers/BasketController.cs
using FoodDelivery.Data;
using FoodDelivery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using FoodDelivery.ViewModels;

public class BasketController : Controller
{
    private readonly ApplicationDbContext _context;

    public BasketController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: Basket
    [HttpGet]
    public IActionResult Index()
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var customer = GetCustomer(userId).Result;

        if (customer != null)
        {
            var orderProducts = _context.OrderProducts
                .Include(op => op.Product)
                .Where(op => op.CustomerId == customer.CustomerId && op.OrderId == null)
                .ToList();

            return View(orderProducts);
        }
        else
        {
            return Redirect("/Identity/Account/Login");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Add(int productId, int quantity)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var customer = await GetCustomer(userId);
        var product = await _context.Products.FindAsync(productId);

        if (product == null)
        {
            return NotFound();
        }

        if (User.IsInRole("Admin") || (customer != null && !User.IsInRole("Courier")))
        {
            var existingOrderProduct = _context.OrderProducts
                .Include(op => op.Product)
                .Where(op => op.OrderId == null && op.ProductId == productId);

            // Perform null check outside of the lambda expression
            existingOrderProduct = customer != null
                ? existingOrderProduct.Where(op => op.CustomerId == customer.CustomerId)
                : existingOrderProduct.Where(op => op.CustomerId == null);

            var firstExistingOrderProduct = existingOrderProduct.FirstOrDefault();

            if (firstExistingOrderProduct != null)
            {
                // If the product is already in the basket, increase the quantity by 1
                firstExistingOrderProduct.Quantity += 1;
                firstExistingOrderProduct.TotalPrice = firstExistingOrderProduct.Quantity * product.Price;
                firstExistingOrderProduct.TotalWeight = firstExistingOrderProduct.Quantity * product.Netto;
            }
            else
            {
                var orderProduct = new OrderProduct
                {
                    Quantity = quantity,
                    TotalPrice = quantity * product.Price,
                    TotalWeight = quantity * product.Netto,
                    ProductId = productId,
                    CustomerId = customer?.CustomerId
                };

                _context.OrderProducts.Add(orderProduct);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }
        else
        {
            return Redirect("/Identity/Account/Login");
        }
    }


    // POST: Basket/Delete/5
    [HttpPost]
    public async Task<IActionResult> Delete(int orderProductId)
    {
        var orderProduct = await _context.OrderProducts
            .Include(op => op.Product)
            .FirstOrDefaultAsync(op => op.OrderProductId == orderProductId);

        if (orderProduct == null)
        {
            return NotFound();
        }

        // Зменшити кількість товару на 1
        if (orderProduct.Quantity > 1)
        {
            orderProduct.Quantity -= 1;
            orderProduct.TotalPrice = orderProduct.Quantity * orderProduct.Product.Price;
            orderProduct.TotalWeight = orderProduct.Quantity * orderProduct.Product.Netto;
        }
        else
        {
            // Якщо кількість дорівнює 1, то видалити повністю
            _context.OrderProducts.Remove(orderProduct);
        }

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> Order()
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var customer = await GetCustomer(userId);
        var orderProducts = await _context.OrderProducts
            .Include(op => op.Product)
            .Where(op => op.CustomerId == customer.CustomerId && op.OrderId == null)
            .ToListAsync();

        var totalOrderPrice = orderProducts.Sum(op => op.TotalPrice);

        var orderViewModel = new OrderViewModel
        {
            OrderProducts = orderProducts.Select(op => new OrderProductViewModel
            {
                ProductId = op.ProductId,
                Name = op.Product.Name,
                Price = op.Product.Price,
                ImageUrl = op.Product.Image,
                Quantity = op.Quantity,
                TotalPrice = op.TotalPrice
            }).ToList(),
            TotalPrice = totalOrderPrice
        };

        // Store the OrderViewModel in TempData
        TempData["OrderViewModel"] = Newtonsoft.Json.JsonConvert.SerializeObject(orderViewModel);

        // Redirect to the OrderController
        return RedirectToAction("Index", "Order");
    }

    private async Task<Customer> GetCustomer(string Id)
    {
        var customer = await _context.Customers
            .FirstOrDefaultAsync(c => c.ApplicationUserId == Id);

        return customer;
    }
}

FoodDl/FoodDelivery/Controllers/OrderController.cs
using FoodDelivery.ViewModels;
using Microsoft.AspNetCore.Mvc;

public class OrderController : Controller
{
    public IActionResult Index()
    {
        // Retrieve the OrderViewModel from TempData
        var orderViewModelJson = TempData["OrderViewModel"] as string;

        if (string.IsNullOrEmpty(orderViewModelJson))
        {
            // Handle the scenario where there are no order products
            return View(new OrderViewModel { OrderProducts = new List<OrderProductViewModel>(), TotalPrice = 0 });
        }

        // Deserialize the JSON string to OrderViewModel
        var orderViewModelObject = Newtonsoft.Json.JsonConvert.DeserializeObject<OrderViewModel>(orderViewModelJson);

        return View(orderViewModelObject);
    }
}

FoodDl/FoodDelivery/Views/Basket/AddToCart.cshtml
@model IEnumerable<Product>

<h2>Add to Cart</h2>

@foreach (var product in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@product.Name</h5>
            <p class="card-text">Price: $@product.Price</p>
            <p class="card-text">Weight: @product.Netto grams</p>
            <form asp-controller="Basket" asp-action="AddToCart" method="post">
                <input type="hidden" name="productId" value="@product.ProductId" />
                <label for="quantity">Quantity:</label>
                <input type="number" name="quantity" value="1" min="1" />
                <button type="submit" class="btn btn-primary">Add to Cart</button>
            </form>
        </div>
    </div>
}

FoodDl/FoodDelivery/Views/Basket/Delete.cshtml
@model int // OrderProductId

<h2>Delete Item</h2>

<form asp-controller="Basket" asp-action="Delete" method="post">
    <input type="hidden" name="orderProductId" value="@Model" />
    <p>Are you sure you want to remove this item from your basket?</p>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

FoodDl/FoodDelivery/Views/Basket/Index.cshtml
@model List<OrderProduct>

<h2 class="lego">Ваша корзина</h2>

<div class="text-center product_template">
        @foreach (var item in Model)
        {
           
            <div class="product-card">
                <img class="product-image" src="@Url.Content($"~/Images/Products/{item.Product.Image}")" alt="Product Image">
            <div class="product-details">

                    <div class="product-title">@item.Product.Name</div>
                    <div class="product-netto">Загальна вага: @item.TotalWeight г</div>
                    <div class="product-category">Кількість: @item.Quantity</div>
                    <div class="product-status">@item.Product.Status</div>
                    <div class="product-price">Загальна ціна: @item.TotalPrice Грн</div>
                    <div>
                        <form asp-controller="Basket" asp-action="Delete" method="post">
                            <input type="hidden" name="orderProductId" value="@item.OrderProductId" />
                            <button type="submit" class="btn btn-danger">Видалити з корзини</button>
                        </form>
                    </div>
                </div>
            </div>
        }
</div>   

@if (Model.Any())
{
    <div class="custom">
    <form asp-controller="Basket" asp-action="Order" method="post">
        <button type="submit" class="btn button-30">Зробити замовлення</button>
    </form>
    </div>
}
else
{
    <p class="lego">Ваша корзина пуста</p>
}

FoodDl/FoodDelivery/Views/Basket/Order.cshtml
<h2>Order Placed</h2>

<p>Thank you for placing your order!</p>
<p>Your order details:</p>

<table class="table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total Price</th>
            <th>Total Weight</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderProducts)
        {
            <tr>
                <td>@item.Product.Name</td>
                <td>@item.Quantity</td>
                <td>@item.TotalPrice</td>
                <td>@item.TotalWeight</td>
            </tr>
        }
    </tbody>
</table>

<p>Total Price: $@Model.TotalPrice</p>
<p>Total Weight: @Model.TotalWeight grams</p>

<a asp-action="Index" class="btn btn-primary">Back to Basket</a>